# -*- coding: utf-8 -*-
{
    'name': "Berdikari",

    'summary': """
        Berdikari Project""",

    'description': """
        Berdikari Project
    """,

    'author': "Juke solutions",
    'website': "http://www.jukesolutions.com",
    'category': 'ERP',
    'version': '0.1',
    'depends': [
        'base',
        'website',
        'web_studio',
        'purchase',
        'hr',
        'hr_expense',
        'hr_attendance',
        'hr_appraisal',
        'hr_payroll',
        'stock_landed_costs',
        'account',
        'account_asset',
        'account_budget',
        'account_accountant',
        'stock',
        'mrp',
        'mrp_plm',
        'sale_management',
        'purchase',
        'point_of_sale',
        'quality_control',
        'maintenance',
        'stock',
        'account_operating_unit',
        'sale_operating_unit',
        'sale_stock_operating_unit',
        'sale_coupon',
        'account_analytic_parent',
        'inputmask_widget',
        'jekdoo',
        'hr_payroll_account',
        'hr_recruitment',
    ],
    'external_dependencies': {
        'python' : ['num2words'],
    },
    'data': [
        'data/ids.xml',
        'security/ir.model.access.csv',
        # 'security/userbiasa.ir.model.access.csv',
        # 'security/rules/stock.picking.xml',
        # 'security/rules/purchase.order.xml',
        # 'security/rules/res.company.xml',
        # 'security/rules/sale.order.xml',
        'data/sequences.xml',
        'security/rules/rules.xml',
        'report/employee_detail_report.xml',
        'report/vendor_bill_report.xml',
        'report/customer_invoice_report.xml',
        'report/internal_transfer_report.xml',
        'report/purchase_request_report.xml',
        'report/purchase_order_template.xml',
        'report/account_invoice_template.xml',
        'report/inventory_adjustment_report.xml',
        'report/employee_bill_report.xml',
        'report/report_financial.xml',
        'report/overtime_letter.xml',
        'report/paklaring.xml',
        'report/payslip.xml',
        'report/payslip_report.xml',
        'report/payslip_byaccount_report.xml',
        'views/contract_type.xml',
        'views/category_type.xml',
        'views/hr_recruitment.xml',
        'views/berdikari_templates.xml',
        'views/menu_atas.xml',
        'views/closing_year.xml',
        'views/cogs_costing.xml',
        'views/subsidiary_company.xml',
        'views/attendance_sheets.xml',
        'views/overtime_request.xml',
        'views/leave_carry_over.xml',
        'views/standard_productivity.xml',
        'views/operational_non_operational.xml',
        'views/institution_type.xml',
        'views/business_unit.xml',
        'views/document_type.xml',
        'views/mode_of_payment.xml',
        'views/employee_paklaring.xml',
        'views/employee_leave.xml',
        'views/attendance_period.xml',
        'views/attendance_code.xml',
        'views/employee_contract.xml',
        'views/punishment_type.xml',
        'views/family_relation.xml',
        'views/competency.xml',
        'views/education_level.xml',
        'views/job_level.xml',
        'views/training_type.xml',
        'views/religion.xml',
        'views/employee.xml',
        'views/breeding_input.xml',
        'views/asset_depreciation.xml',
        'views/asset_write_off.xml',
        'views/generate_assets_entries.xml',
        'views/asset_biologis_used.xml',
        'views/work_order.xml',
        'views/asset_reclass.xml',
        'views/asset_adding.xml',
        'views/phase.xml',
        'views/farm_machine.xml',
        'views/farm.xml',
        'views/purchase_order.xml',
        'views/purchase_request.xml',
        'views/partner.xml',
        'views/budget.xml',
        'views/chart_of_account.xml',
        'views/account_invoice.xml',
        'views/vendor_bill.xml',
        'views/customers_payment.xml',
        'views/receipts.xml',
        'views/assets.xml',
        'views/inventory_adjustment.xml',
        'views/product.xml',
        'views/scrap.xml',
        'views/account_payment.xml',
        'views/journal_entry.xml',
        'views/tax_adjustment.xml',
        'views/vat_management.xml',
        'views/landed_cost.xml',
        'views/hose_master.xml',
        'views/flock_master.xml',
        'views/stock.xml',
        'views/sale.xml',
        'views/fms_breeding.xml',
        'views/fms_egg_production.xml',
        'views/fms_grading_setter.xml',
        'views/fms_grading_hatcher.xml',
        # 'views/fms_hatchery.xml',
        'views/payment_request.xml',
        'views/users.xml',
        'views/invoice.xml',
        'views/stock_location.xml',
        'views/report_pph.xml',
        'views/report_down_payment.xml',
        'views/report_receive_money.xml',
        'views/jekdoo_setup.xml',
        'views/account_bank_statement.xml',
        'views/employee_kasbon.xml',
        'views/sale_coupon_program.xml',
        'views/res_currency_view.xml',
        'views/res_company.xml',
        'views/stock_scrap.xml',
        'views/job.xml',
        'views/res_config_settings_views.xml',
        'views/hr_department.xml',
        'views/summary_attendance.xml',
        'views/salary_rule.xml',
        'views/hr_payslip.xml',
        'views/hr_payslip_filter.xml',
        'views/hr_payslip_byaccount.xml',
        'views/ir_attachment.xml',
        'views/menu.xml',
        'views/menu_hris.xml',
    ],
    'qweb': [
        'static/custom/xml/datepicker.xml',
        'static/custom/xml/custom_berdikari_templates.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'sequence': 1,
}
#NOTE - jacky
