# -*- coding: utf-8 -*-

from . import users
from . import purchase_order
from . import purchase_request
from . import employee_appraisal
from . import employee_leave
from . import employee_education
from . import employee_training
from . import employee_family
from . import employee_emergency_contact
from . import employee_work
from . import employee_medical
from . import employee_reward
from . import employee_punishment
from . import employee_paklaring
from . import employee_contract
from . import employee
from . import customers
from . import budget
from . import chart_of_account
from . import asset
from . import inventory_receipts
from . import product
from . import tax_adjustment
from . import vat_management
from . import account_payment
from . import partner
from . import landed_cost
from . import hose_master
from . import stock
from . import stock_picking
from . import flock_master
from . import account_move
from . import fms_breeding
from . import account_invoice
from . import account_move
from . import sale
from . import fms_egg_production
# from . import fms_hatchery
# from . import fms_hatchery_setter
# from . import fms_hatchery_hatcher
from . import fms_grading_setter
from . import fms_grading_hatcher
# from . import fms_hatchery_grading
from . import payment_request
from . import farm
from . import farm_machine
from . import phase
from . import asset_adding
from . import asset_reclass
from . import work_order_batch
from . import work_order
from . import asset_biologis_used
from . import generate_assets_entries
from . import asset_write_off
from . import asset_depreciation
from . import breeding_input
from . import religion
from . import training_type
from . import job_level
from . import education_level
from . import competency
from . import family_relation
from . import punushment_type
from . import attendance_code
from . import attendance_period
from . import fms_hatchery_setter
from . import fms_hatchery_hatcher
from . import mode_of_payment
from . import document_type
from . import business_unit
from . import institution_type
from . import operational_non_operational
from . import standard_productivity
from . import leave_carry_over
from . import overtime_request
from . import attendance_sheets
from . import jekdoo_setup
from . import subsidiary_company
from . import cogs_costing
from . import closing_year
from . import invoice
from . import stock_location
from . import report_pph
from . import account_bank_statement
from . import account_journal
from . import sale_coupon_program
from . import wizard_receive_money
from . import account_report
from . import account_account
from . import company
from . import res_currency
from . import stock_scrap
from . import job
from . import hr_department
from . import account_aged_partner_balance
from . import summary_attendance
from . import hr_leave
from . import salary_rule
from . import hr_payslip
from . import hr_payslip_filter
from . import hr_payslip_byaccount
from . import category_type
from . import contract_type
from . import ir_attachment